<div id="sign-up">
	<h2>Join us</h2>
			

		<form action="/Members/signUp" method="post">
		<input type="text" name="pseudo" placeholder="Pseudo">
		<input type="text" name="email" placeholder="Email">
		<input type="password" name="pass" placeholder="Password">
		<input type="password" name="pass_confirm" placeholder="Confirme Password">
		<select name="sex">
			<option type="text" value="M">Male</option>
			<option type="text" value="F">Female</option>
		</select>
		<input type="submit" name="signup" value="Sign Up">		
	</form>
</div><!--end of join-us-->