
<div class="user-edit">
	<form action="/Profile/editProfil" method="post">
	<table>
		<tr>
			<td>
				<h1>Pseudo</h1>
				<input type="text" name="pseudo" placeholder="<?php echo $_SESSION['pseudo']?>">
				<h2>Email :</h2>
				<input type="email" name="email" placeholder="<?php echo $_SESSION['email']?>">
				<h2>Website : </h2>
				<input type="text" name="website" placeholder="<?php echo $_SESSION['website']?>">
			</td>
			<td>
				<img src="/images/profiles/profile<?php echo $_SESSION['idMember'];?>.jpg">
				<input type="file" name="nom" />
			</td>
		</tr>
	</table>
	<h2 class="description">Description :</h2>
	<textarea name="description" cols="54" rows="9" placeholder="<?php echo $_SESSION['description']?>"></textarea>
	<input id="edit" type="submit" name="Edit" value="Edit profil">
	</form>
</div>